routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


 Route::get('/', function () {
     return redirect()->route('home.home');
 });

Route::group(['controller'=>'PlatformsController','as'=>'platforms.','prefix'=>'platforms'],function(){
    Route::get('index','index')->name('index');
    Route::get('getPlatforms','getPlatforms')->name('getPlatforms');
    Route::post('add','add')->name('add');
    Route::match(['post','get'],'edit/{id}','edit')->name('edit');
    Route::delete('delete/{id}','delete')->name('delete');
    Route::get('bin','bin')->name('bin');
    Route::get('getPlatformsDeleted','getPlatformsDeleted')->name('getPlatformsDeleted');
    Route::post('restore/{id}','restore')->name('restore');
    Route::delete('forceDelete/{id}','forceDelete')->name('forceDelete');
});

Route::group(['controller'=>'UsersController','as'=>'users.','prefix'=>'users'],function(){
    Route::get('index','index')->name('index');
    Route::get('getUsers','getUsers')->name('getUsers');
    Route::post('add','add')->name('add');
    Route::match(['post','get'],'edit/{id}','edit')->name('edit');
    Route::delete('delete/{id}','delete')->name('delete');
    Route::match(['post','get'],'forgotpassword','forgotpassword')->name('forgotpassword');
    Route::match(['post','get'],'resetpassword/{token}','resetpassword')->name('resetpassword');
});

Route::group(['controller'=>'VideoHeadersController','as'=>'video-headers.','prefix'=>'video-headers'],function(){
    Route::get('index','index')->name('index');
    Route::get('getVideoHeaders','getVideoHeaders')->name('getVideoHeaders');
    Route::post('add','add')->name('add');
    Route::match(['post','get'],'edit/{id}','edit')->name('edit');
    Route::delete('delete/{id}','delete')->name('delete');
    Route::get('bin','bin')->name('bin');
    Route::get('getTrashedVideoHeaders','getTrashedVideoHeaders')->name('getTrashedVideoHeaders');
    Route::post('restore/{id}','restore')->name('restore');
    Route::delete('forceDelete/{id}','forceDelete')->name('forceDelete');
});

Route::group(['controller'=>'VideosController','as'=>'videos.','prefix'=>'videos'],function(){
    Route::get('index','index')->name('index');
    Route::get('getVideos','getVideos')->name('getVideos');
    Route::get('getVideoPlatforms/{id}','getVideoPlatforms')->name('getVideoPlatforms');
    Route::post('add','add')->name('add');
    Route::match(['post','get'],'edit/{id}','edit')->name('edit');
    Route::delete('delete/{id}','delete')->name('delete');
    Route::get('bin','bin')->name('bin');
    Route::get('getVideosDeleted','getVideosDeleted')->name('getVideosDeleted');
    Route::post('restore/{id}','restore')->name('restore');
    Route::delete('forceDelete/{id}','forceDelete')->name('forceDelete');
});

Route::group(['controller'=>'HomeController','as'=>'home.','prefix'=>'home'],function(){
    Route::get('about','about')->name('about');
    Route::get('video/{id}','video')->name('video');
    Route::match(['post','get'],'home','home')->name('home');
    Route::get('autocomplete','autocomplete')->name('autocomplete');
});

// Route::controller(MailerController::class)->prefix('mail')->name('mail.')->group(function(){
//     Route::get('send-mail', 'sendMail')->name('send-mail');
//     Route::get('send-mail-link', 'sendMailLink')->name('send-mail-link');
// });

Auth::routes();


//Route::get('/', [App\Http\Controllers\PlatformsController::class, 'index'])->name('index');

// Route::get('/', [App\Http\Controllers\PlatformsController::class, 'index'])->name('index');

resources/views/element/admin/footer.blade.php
<div class="container-fluid">
    <footer class="footer">
        <div class="card">
            <div class="card-body">
                <div class="d-sm-flex justify-content-center justify-content-sm-between">
                    <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © 2020</span>
                    <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Distributed By: <a href="https://www.themewagon.com/" target="_blank">Brain Network Japan</a></span>
                </div>
            </div>
        </div>
    </footer>
</div>

resources/views/element/admin/navbar.blade.php
<nav class="navbar col-lg-12 col-12 px-0 py-0 py-lg-4 d-flex flex-row">
    <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">

        <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="mdi mdi-menu"></span>
        </button>
        <script>
            $(function () {
               $('button[data-toggle="minimize"]').on('click',function () {
                   $('body').toggleClass('sidebar-icon-only');
               });
            });
        </script>

        <div class="navbar-brand-wrapper">
            <a class="navbar-brand brand-logo" href="javascript:void(0)">
                {{-- <img src="{{asset('images/logo.svg')}}" alt=""/> --}}
                <img src="{{asset('images/Philippines.png')}}" alt="logo">
            </a>
            <a class="navbar-brand brand-logo-mini" href="javascript:void(0)">
                <img src="{{asset('images/logo-mini.svg')}}" alt="">
            </a>
        </div>
        {{-- {{ auth()->user()->username }} --}}
        <h4 class="font-weight-bold mb-0 d-none d-md-block mt-1">Welcome back, {{ Auth::check() ? ucfirst(Auth::user()->username) : 'You are not logged in' }}</h4>
        <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item">
                <h4 class="mb-0 font-weight-bold d-none d-xl-block" id="date-time">
                    <script>
                        var date = moment().format('YYYY, MMMM D, hh:mm s A');
                        document.write(date);
                    </script>
                </h4>
                <script>
                    var datetime = document.querySelector('#date-time');
                    setInterval(function () {
                        var date = moment().format('YYYY, MMMM D, hh:mm s A');
                        datetime.innerText = date;
                    },1000);

                </script>
            </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="mdi mdi-menu"></span>
        </button>
    </div>
    <div class="navbar-menu-wrapper navbar-search-wrapper d-none d-lg-flex align-items-center">
        <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item nav-profile dropdown">
                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
                        <img src="{{asset('images/faces/face28.jpg')}}" alt="profile"/>
                    <span class="nav-profile-name">{{ Auth::check() ? Auth::user()->email : 'You are not logged in' }}</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
                    <a class="dropdown-item" href="{{ route('logout') }}"
                        onclick="event.preventDefault();
                                        document.getElementById('logout-form').submit();">
                        <i class="mdi mdi-logout text-primary"></i>{{ __('Logout') }}
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                        @csrf
                    </form>

                    {{-- <a class="dropdown-item">
                        <i class="mdi mdi-logout text-primary"></i>
                        Logout
                    </a> --}}

                </div>
            </li>
            <li class="nav-item">
                <a href="{{route('home.home')}}" title="Go To Web" class="nav-link icon-link">
                    <i class="mdi mdi-web"></i>
                </a>
            </li>
        </ul>
    </div>
</nav>

resources/views/element/admin/sidebar.blade.php
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item sidebar-category">
            <p>Navigation</p>
            <span></span>
        </li>
        <li class="nav-item {{url()->current() == route('users.index')? 'active': ''}}">
            <a class="nav-link" href="{{route('users.index')}}">
                <i class="mdi mdi-account-box menu-icon"></i>
                <span class="menu-title">Users</span>
            </a>
        </li>
        <li class="nav-item {{url()->current() == route('platforms.index')? 'active': ''}}">
            <a class="nav-link" href="{{route('platforms.index')}}">
                <i class="mdi mdi-view-quilt menu-icon"></i>
                <span class="menu-title">Platforms</span>
            </a>
        </li>
        <li class="nav-item {{url()->current() == route('video-headers.index')? 'active': ''}}">
            <a class="nav-link" href="{{route('video-headers.index')}}">
                <i class="mdi mdi-video menu-icon"></i>
                <span class="menu-title">Video Headers</span>
            </a>
        </li>
        <li class="nav-item {{url()->current() == route('videos.index')? 'active': ''}}">
            <a class="nav-link" href="{{route('videos.index')}}">
                <i class="mdi mdi-file-video menu-icon"></i>
                <span class="menu-title">Videos</span>
            </a>
        </li>
        <li class="nav-item  {{in_array(url()->current(),[
                                    route('platforms.bin'),
                                    route('videos.bin'),
                                    route('video-headers.bin')
                                    ])? 'active': ''}}">
            <a class="nav-link" data-toggle="collapse" href="#auth" aria-expanded="false" aria-controls="auth">
                <i class="mdi mdi-eraser-variant menu-icon"></i>
                <span class="menu-title">Bin</span>
                <i class="menu-arrow"></i>
            </a>
            <div class="collapse {{in_array(url()->current(),[
                                    route('platforms.bin'),
                                    route('videos.bin'),
                                    route('video-headers.bin')
                                    ])? 'show': ''}}"
                 id="auth">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('platforms.bin')}}">
                            Platforms
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('videos.bin')}}">
                            Videos
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('video-headers.bin')}}">
                            Video Headers
                        </a>
                    </li>
                </ul>
            </div>
        </li>
    </ul>
</nav>